# app.yaml - Configuration for Google App Engine
runtime: nodejs18
service: dev

env_variables:
  GOOGLE_CLIENT_ID: "294376282666-lllnj1ro4d5qu3iq21nmmasr16tjije5.apps.googleusercontent.com"

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /static
    static_dir: public/static
    secure: always

  - url: /(.*\.(json|ico|js|css|png|jpg|gif|svg|woff|woff2|ttf|eot))$
    static_files: public/\1
    upload: public/.*\.(json|ico|js|css|png|jpg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    script: auto
    secure: always