# app.yaml - Configuration for Google App Engine
runtime: nodejs16

env_variables:
  GOOGLE_CLIENT_ID: "294376282666-lllnj1ro4d5qu3iq21nmmasr16tjije5.apps.googleusercontent.com"

indexes:
- kind: Notebook
  properties:
  - name: createdBy
  - name: name
    direction: asc

- kind: Progress
  properties:
  - name: userEmail
  - name: notebookId

- kind: User
  properties:
  - name: email
  - name: role

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /static
    static_dir: public/static
    secure: always

  - url: /(.*\.(json|ico|js|css|png|jpg|gif|svg|woff|woff2|ttf|eot))$
    static_files: public/\1
    upload: public/.*\.(json|ico|js|css|png|jpg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    script: auto
    secure: always